---
- name: Update remote
  ansible.builtin.apt:
    update_cache: true
    autoclean: true
    autoremove: true
    upgrade: "dist"

- name: Install required packages
  ansible.builtin.apt:
    pkg: "{{ required_server_packages }}"

- name: Add the user
  ansible.builtin.user:
    name: "{{ user_name }}"
    shell: /bin/bash
    groups: sudo
    append: true

- name: Delete manifest dirs in working dir
  ansible.builtin.file:
    state: absent
    path: "{{ work_dir }}/{{ item }}"
  loop: "{{ relevant_code_dirs }}"

- name: Copy manifests to remote
  ansible.builtin.synchronize:
    src: "{{ playbook_dir | dirname }}/{{ item }}"
    dest: "{{ work_dir }}"
  loop: "{{ relevant_code_dirs }}"

- name: Allow pod CIDR through UFW
  community.general.ufw:
    rule: allow
    src: "{{ item.cidr }}"
    comment: "{{ item.comment }}"
  loop:
    - { cidr: "{{ cilium_pod_cidr }}", comment: "Cilium pod CIDR" }
    - { cidr: "{{ k3s_service_cidr }}", comment: "k3s service CIDR" }

- name: Install and configure k3s
  ansible.builtin.include_role:
    name: setup_k3s

- name: Generate SSL certificates
  ansible.builtin.include_role:
    name: generate_certs
  vars:
    certs_base_dir: "{{ work_dir }}"

- name: Set ownership of {{ work_dir }}
  ansible.builtin.file:
    path: "{{ work_dir }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"
    recurse: true

- name: Deploy Kubernetes manifests
  ansible.builtin.include_role:
    name: deploy_k8s
  vars:
    certs_base_dir: "{{ work_dir }}"
