FROM sonarsource/sonar-scanner-cli

RUN apk add --update nodejs npm

RUN npm install -g yarn

COPY . .

ENV NODE_PATH=./src

RUN yarn install 

RUN npm init @eslint/config -y

# RUN mv docker/sonar-project.properties .

# RUN mv docker/.eslintrc .

# RUN mv docker/sonar-test.sh .

CMD ["sh", "sonar-test.sh"]